# Generated by Django 3.0.6 on 2020-08-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
    ]
